// ********RoostGPT********
// Test generated by RoostGPT for test java-customannotation-test using AI Type  and AI Model 



// ********RoostGPT********
// src/__tests__/reportWebVitals.test.js
import reportWebVitals from '../../src/reportWebVitals';

describe('reportWebVitals', () => {
    test('should exist as a function', () => {
        expect(typeof reportWebVitals).toBe('function');
    });

    test('should not throw an error when called', () => {
        expect(() => {
            reportWebVitals(console.log);
        }).not.toThrow();
    });
});

